language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: COVERALLS=1 DEFAULT=0

    - php: 5.6
      env: PREFER_LOWEST=1

before_script:
  # we do only need xdebug on the version where we want code coverage
  # xdebug is not released for PHP 7.3 so we cannot remove it
  - if [[ $TRAVIS_PHP_VERSION != 7.2 && $TRAVIS_PHP_VERSION != 7.3 ]]; then phpenv config-rm xdebug.ini; fi

  - if [[ $PREFER_LOWEST != 1 ]]; then composer update --no-interaction ; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --no-interaction --prefer-lowest --prefer-stable; fi

  - if [[ $PHPCS == 1 ]]; then composer require cakephp/cakephp-codesniffer:"^3.0"; fi

  - if [[ $COVERALLS == 1 ]]; then composer require --dev php-coveralls/php-coveralls; fi
  - if [[ $COVERALLS == 1 ]]; then mkdir -p build/logs; fi

script:
  - if [[ i$DEFAULT == 1  ]]; then vendor/bin/phpunit; fi
  
  - if [[ $COVERALLS == 1 ]]; then vendor/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ $COVERALLS == 1 ]]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi

  - if [[ $PHPCS == 1 ]]; then vendor/bin/phpcs -n -p --extensions=php  --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests; fi

notifications:
  email: false
